version: "3.8"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
